import PDFDocument from 'pdfkit';

/**
 * Renders a one-page media kit PDF straight to an HTTP response stream, using
 * only the creator's own real profile data. No fabricated stats — a field is
 * simply omitted from the PDF if the profile doesn't have it.
 */
export async function renderMediaKitPdf(profile, res) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  doc.pipe(res);

  // Header
  doc.fontSize(24).fillColor('#7C3AED').text(profile.displayName || 'Creator', { continued: false });
  if (profile.headline) doc.fontSize(13).fillColor('#4B5563').text(profile.headline);
  const location = [profile.location?.city, profile.location?.country].filter(Boolean).join(', ');
  if (location) doc.fontSize(11).fillColor('#6B7280').text(location);
  doc.moveDown(1);

  // Bio
  if (profile.bio) {
    doc.fontSize(12).fillColor('#111827').text(profile.bio, { width: 495 });
    doc.moveDown(1);
  }

  // Categories
  if (profile.categories?.length) {
    doc.fontSize(11).fillColor('#7C3AED').text('Categories', { underline: false });
    doc.fontSize(11).fillColor('#111827').text(profile.categories.join('  ·  '));
    doc.moveDown(1);
  }

  // Social stats table (real synced data only)
  if (profile.socialAccounts?.length) {
    doc.fontSize(14).fillColor('#7C3AED').text('Social Reach');
    doc.moveDown(0.3);
    const startY = doc.y;
    const colW = [140, 140, 120, 100];
    const headers = ['Platform', 'Handle', 'Followers', 'Eng. Rate'];
    let x = 50;
    doc.fontSize(10).fillColor('#6B7280');
    headers.forEach((h, i) => { doc.text(h, x, startY); x += colW[i]; });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#111827');
    for (const s of profile.socialAccounts) {
      const y = doc.y;
      x = 50;
      doc.text(s.platform, x, y); x += colW[0];
      doc.text(s.handle || '—', x, y); x += colW[1];
      doc.text((s.followers ?? 0).toLocaleString('en-IN'), x, y); x += colW[2];
      doc.text(`${s.engagementRate ?? 0}%`, x, y);
      doc.moveDown(0.6);
    }
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor('#9CA3AF').text(
      `Total audience: ${(profile.totalAudience ?? 0).toLocaleString('en-IN')}   ·   Avg. engagement: ${profile.avgEngagement ?? 0}%`,
    );
    doc.moveDown(1);
  }

  // Rate card (real, creator-set values only)
  if (profile.rateCard?.length) {
    doc.fontSize(14).fillColor('#7C3AED').text('Rate Card');
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#111827');
    for (const r of profile.rateCard) {
      doc.text(`${r.contentType}  —  ₹${(r.price ?? 0).toLocaleString('en-IN')}`);
    }
    doc.moveDown(1);
  }

  // Portfolio (titles + platform only — embedding remote images would need a
  // network fetch per item; omitted here to keep generation fast/offline-safe,
  // left as a documented follow-up in the changelog).
  if (profile.portfolio?.length) {
    doc.fontSize(14).fillColor('#7C3AED').text('Portfolio Highlights');
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#111827');
    for (const p of profile.portfolio.slice(0, 8)) {
      doc.text(`• ${p.title || p.platform || 'Untitled piece'}`);
    }
    doc.moveDown(1);
  }

  doc.fontSize(9).fillColor('#9CA3AF').text('Generated by Marqueiver', 50, 780, { width: 495, align: 'center' });
  doc.end();
}
