import { Router } from 'express';
import authRoutes from './modules/auth/auth.routes.js';
import userRoutes from './modules/users/users.routes.js';
import discoveryRoutes from './modules/discovery/discovery.routes.js';
import dealRoutes from './modules/deals/deals.routes.js';
import messagingRoutes from './modules/messaging/messaging.routes.js';
import paymentRoutes from './modules/payments/payments.routes.js';
import reviewRoutes from './modules/reviews/reviews.routes.js';
import verificationRoutes from './modules/verifications/verifications.routes.js';
import notificationRoutes from './modules/notifications/notifications.routes.js';
import aiRoutes from './modules/ai/ai.routes.js';
import adminRoutes from './modules/admin/admin.routes.js';
import instagramRoutes from './modules/instagram/instagram.routes.js';
import youtubeRoutes from './modules/youtube/youtube.routes.js';
import facebookRoutes from './modules/facebook/facebook.routes.js';
import campaignsRoutes from './modules/campaigns/campaigns.routes.js';
import walletRoutes from './modules/wallet/wallet.routes.js';
const api = Router();
api.use('/auth', authRoutes);
// Instagram routes register both /auth/instagram* and /instagram* per SRS §5.
api.use('/', instagramRoutes);
api.use('/users', userRoutes);
api.use('/discovery', discoveryRoutes);
api.use('/deals', dealRoutes);
api.use('/campaigns', campaignsRoutes);
api.use('/wallet', walletRoutes);
api.use('/messages', messagingRoutes);
api.use('/payments', paymentRoutes);
api.use('/reviews', reviewRoutes);
api.use('/verifications', verificationRoutes);
api.use('/notifications', notificationRoutes);
api.use('/ai', aiRoutes);
api.use('/admin', adminRoutes);
api.use('/', youtubeRoutes);
api.use('/', facebookRoutes);
export default api;
