import { Router } from 'express';
import { authenticate } from '../../middleware/auth.js';
import { validate } from '../../middleware/validate.js';
import * as c from './users.controller.js';
const router = Router();
router.use(authenticate);
router.get('/me/profile', c.getMyProfile);
router.patch('/me/creator', validate(c.updateCreatorSchema), c.updateCreatorProfile);
router.patch('/me/brand', validate(c.updateBrandSchema), c.updateBrandProfile);
router.post('/me/socials', validate(c.connectSocialSchema), c.connectSocial);
router.post('/me/ai-analysis', c.runAiAnalysis);
router.post('/me/logo-upload-url', validate(c.getUploadUrlSchema), c.getLogoUploadUrl);
router.post('/me/complete-onboarding', c.completeOnboarding);
router.patch('/me/onboarding-step', validate(c.saveOnboardingStepSchema), c.saveOnboardingStep);
router.post('/me/portfolio', validate(c.addPortfolioItemSchema), c.addPortfolioItem);
router.delete('/me/portfolio/:itemId', c.deletePortfolioItem);
router.get('/me/analytics', c.getAnalytics);
router.get('/me/media-kit', c.getMediaKit);
export default router;
